package interfaz;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.*;
import obligatoriop2.*;

public class JFrameRanking extends javax.swing.JDialog {
    private JList lista;
    private Juego juego;
    private ArrayList<Jugador> ranking;
    
    
    public JFrameRanking(Juego unJuego) {
        initComponents();
        
        this.setModal(true);
        this.setSize(780, 300);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        this.btnVolver.setSize(100,30);
        
        this.juego = unJuego;
        ranking = juego.getListaJugadores();
        Collections.sort(ranking);
        ranking.toArray();       
        this.panelRanking.setLayout(new GridLayout(ranking.toArray().length, 1, 0, 10));
            for (int i = ranking.toArray().length; i > 0; i--) {
                        JLabel label = new JLabel((Math.abs(i - ranking.toArray().length -1)) 
                                + "º) " + ranking.toArray()[i-1].toString());
                        panelRanking.add(label);
                    
            }
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        panelRanking = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/BtnVolver (2).png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(600, 210, 133, 39);

        panelRanking.setBackground(new java.awt.Color(0, 204, 153));

        javax.swing.GroupLayout panelRankingLayout = new javax.swing.GroupLayout(panelRanking);
        panelRanking.setLayout(panelRankingLayout);
        panelRankingLayout.setHorizontalGroup(
            panelRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        panelRankingLayout.setVerticalGroup(
            panelRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        getContentPane().add(panelRanking);
        panelRanking.setBounds(0, 50, 770, 145);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Ranking");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 10, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/FondoRanking.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        String[] sino = {"Si","No"};
        int eleccion = JOptionPane.showOptionDialog(this, 
            "¿Está seguro que desea volver al menú principal?",
            "¿Desea volver al menú anterior?",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            sino,
            "Si");
        if (eleccion == 0){
            this.dispose();
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelRanking;
    // End of variables declaration//GEN-END:variables
}
