package interfaz;

import javax.swing.JOptionPane;
import obligatoriop2.*;

/**
 *
 * @author Allen
 */
public class JFrameRegistroDeJugador extends javax.swing.JDialog {

    /**
     * Creates new form JFrameRegistroDeJugador
     */
    private Juego juego;
    private Jugador nuevoJugador;
    private boolean edadValida;
    
    public JFrameRegistroDeJugador(Juego unJuego) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.juego = unJuego;
        Jugador nuevoJugador = new Jugador();
        this.nuevoJugador = nuevoJugador;
        this.setEdadValida(false);
        mensajeNombre.setVisible(false);
        mensajeAlias.setVisible(false);
        mensajeEdad.setVisible(false);
        
        this.btnRegistrar.setSize(100, 30);
        this.btnVolver.setSize(100, 30);
        
        this.setSize(400, 320);
        this.setModal(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        btnVolver.requestFocus();
    }

    public boolean campoEstaVacio(String unTexto) {
        return unTexto.trim().isEmpty();
    }
    
    public boolean esEntero(String s) {
    try { 
        Integer.parseInt(s); 
    } catch(NumberFormatException e) { 
        return false; 
    }
    return true;
}
    
    public void setEdadValida(boolean unBoolean){
        this.edadValida = unBoolean;
    }
    
    public boolean getEdadValida(){
        return this.edadValida;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        txtAlias = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        mensajeAlias = new javax.swing.JLabel();
        mensajeNombre = new javax.swing.JLabel();
        mensajeEdad = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        txtAlias.setText("Ingrese su alias aquí");
        txtAlias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAliasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAliasFocusLost(evt);
            }
        });
        txtAlias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAliasActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlias);
        txtAlias.setBounds(95, 126, 139, 41);

        txtEdad.setText("Ingrese su edad aquí");
        txtEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEdadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEdadFocusLost(evt);
            }
        });
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        getContentPane().add(txtEdad);
        txtEdad.setBounds(95, 178, 139, 41);

        txtNombre.setText("Ingrese su nombre aquí");
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(95, 74, 139, 41);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 74, 60, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Alias:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 140, 50, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Edad:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 190, 34, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registro de Jugador:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 11, 380, 36);

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/BtnRegistrar (2).png"))); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(100, 240, 110, 20);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/BtnVolver (2).png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(280, 250, 110, 39);

        mensajeAlias.setText("El alias ya ha sido tomado");
        getContentPane().add(mensajeAlias);
        mensajeAlias.setBounds(238, 126, 152, 41);

        mensajeNombre.setText("Debe ingresar su nombre");
        getContentPane().add(mensajeNombre);
        mensajeNombre.setBounds(238, 74, 152, 41);

        mensajeEdad.setText("Debe ingresar su edad");
        getContentPane().add(mensajeEdad);
        mensajeEdad.setBounds(238, 178, 152, 41);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed

    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtEdadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdadFocusGained
        boolean primeraVez = false;
        if (!primeraVez) {
            txtEdad.setText("");
            primeraVez = true;
        }
    }//GEN-LAST:event_txtEdadFocusGained

    private void txtAliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAliasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAliasActionPerformed

    private void txtAliasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAliasFocusGained
        boolean primeraVez = false;
        if (!primeraVez) {
            txtAlias.setText("");
            primeraVez = true;
        }
    }//GEN-LAST:event_txtAliasFocusGained

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        boolean primeraVez = false;
        if (!primeraVez) {
            txtNombre.setText("");
            primeraVez = true;
        }
    }//GEN-LAST:event_txtNombreFocusGained

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        txtAliasFocusLost(null);
        txtNombreFocusLost(null);
        txtEdadFocusLost(null);
        
        if (this.campoEstaVacio(txtAlias.getText()) || this.campoEstaVacio(txtNombre.getText())
                || this.campoEstaVacio(txtEdad.getText())) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben \n"
                    + "estar rellenados");
        } else if (!this.juego.aliasValido(nuevoJugador)) {
            JOptionPane.showMessageDialog(this, "El alias debe ser único, \n"
                    + "por favor ingrese uno nuevo");
        
        }else if(!this.getEdadValida() && !esEntero(txtEdad.getText())){
            JOptionPane.showMessageDialog(this, "La edad debe estar expresada en números, \n"
                    + "por favor ingresela nuevamente");
        } 
        else if(!this.getEdadValida() && esEntero(txtEdad.getText())){
            JOptionPane.showMessageDialog(this, "La edad debe estar expresada en números enteros positivos");
        }
        else{
            this.nuevoJugador.setNombre(txtNombre.getText());
            this.nuevoJugador.setEdad(Integer.parseInt(txtEdad.getText()));
            this.juego.agregarJugador(nuevoJugador);
            JOptionPane.showMessageDialog(this, "Registro exitoso");
            this.dispose();  
        }   
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtAliasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAliasFocusLost
        this.nuevoJugador.setAlias(txtAlias.getText());
        if (!juego.aliasValido(nuevoJugador)) {
            mensajeAlias.setText("El alias ya ha sido tomado");
            mensajeAlias.setVisible(true);
        } else if (juego.aliasValido(nuevoJugador)) {
            mensajeAlias.setVisible(false);
        }

        if (this.campoEstaVacio(txtAlias.getText())) {
            mensajeAlias.setVisible(true);
            mensajeAlias.setText("Debe ingresar un alias");
        } else if (!this.campoEstaVacio(txtAlias.getText())) {
            mensajeNombre.setVisible(false);
        }
    }//GEN-LAST:event_txtAliasFocusLost

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        if (this.campoEstaVacio(txtNombre.getText())) {
            mensajeNombre.setVisible(true);
        } else if (!this.campoEstaVacio(txtNombre.getText())) {
            mensajeNombre.setVisible(false);
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtEdadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdadFocusLost
        if (this.campoEstaVacio(txtEdad.getText())) {
            mensajeEdad.setText("Debe ingresar su edad");
            mensajeEdad.setVisible(true);
            this.setEdadValida(false);
        }else if (this.esEntero(txtEdad.getText()) && Integer.parseInt(txtEdad.getText()) < 0) {
            this.setEdadValida(false);
            mensajeEdad.setText("Edad invalida.");
            mensajeEdad.setVisible(true);
        }
        else if (!this.campoEstaVacio(txtEdad.getText()) && !this.esEntero(txtEdad.getText())){
            mensajeEdad.setText("Su edad solo debe contener numeros");
            mensajeEdad.setVisible(true);
            this.setEdadValida(false);
        }
        else if (!this.campoEstaVacio(txtEdad.getText()) && this.esEntero(txtEdad.getText())){
            mensajeEdad.setVisible(false);
            this.setEdadValida(true);
        }
        
    }//GEN-LAST:event_txtEdadFocusLost

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        String[] sino = {"Si","No"};
        int eleccion = JOptionPane.showOptionDialog(this, 
            "¿Está seguro que desea volver al menú principal?\n"
            + "Si no ha presionado el boton registrar\n"
            + "todos los datos se perderán.",
            "¿Desea volver al menú anterior?",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            sino,
            "Si");
        if (eleccion == 0){
            this.dispose();
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel mensajeAlias;
    private javax.swing.JLabel mensajeEdad;
    private javax.swing.JLabel mensajeNombre;
    private javax.swing.JTextField txtAlias;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
