package interfaz;

import javax.swing.*;
import obligatoriop2.*;

public class JFramePrePartida extends javax.swing.JDialog {

    private ButtonGroup grupoBotones;
    private Partida partida;
    private Juego juego;

    public JFramePrePartida(Juego unJuego, Partida unaPartida) {
        initComponents();
        
        this.setModal(true);
        this.setSize(400, 350);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        this.btnJugar.setSize(100, 30);
        this.btnVolver.setSize(100, 30);
        
        
        this.juego = unJuego;
        this.partida = unaPartida;
        grupoBotones = new ButtonGroup();
        grupoBotones.add(rbtnTres);
        grupoBotones.add(rbtnCinco);
        this.mensajeAlerta.setVisible(false);
        DefaultListModel dlm = new DefaultListModel();
        for (int i = 0; i < this.juego.getListaJugadores().size(); i++) {
            dlm.addElement(this.juego.getListaJugadores().get(i).getAlias());
        }
        this.listaJ1.setModel(dlm);
        this.listaJ2.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaJ1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaJ2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        rbtnTres = new javax.swing.JRadioButton();
        rbtnCinco = new javax.swing.JRadioButton();
        btnJugar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        mensajeAlerta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione el Jugador 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 190, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Seleccione el Jugador 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 20, 170, 17);

        listaJ1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaJ1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                listaJ1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(listaJ1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(55, 44, 112, 146);

        listaJ2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaJ2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                listaJ2FocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(listaJ2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(228, 44, 112, 146);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tamaño del Tablero");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(5, 205, 150, 20);

        rbtnTres.setBackground(new java.awt.Color(0, 153, 153));
        rbtnTres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtnTres.setText("3x3");
        rbtnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTresActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnTres);
        rbtnTres.setBounds(167, 201, 50, 25);

        rbtnCinco.setBackground(new java.awt.Color(0, 153, 153));
        rbtnCinco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtnCinco.setText("5x5");
        rbtnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCincoActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnCinco);
        rbtnCinco.setBounds(167, 227, 50, 25);

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/btnJugar (2).png"))); // NOI18N
        btnJugar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnJugar.setMinimumSize(new java.awt.Dimension(100, 30));
        btnJugar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar);
        btnJugar.setBounds(270, 260, 133, 39);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/BtnVolver (2).png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(10, 260, 110, 30);

        mensajeAlerta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mensajeAlerta.setText("Este jugadorya ha sido seleccionado");
        getContentPane().add(mensajeAlerta);
        mensajeAlerta.setBounds(169, 180, 210, 14);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTresActionPerformed
        partida.crearTablero(3);
    }//GEN-LAST:event_rbtnTresActionPerformed

    private void rbtnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCincoActionPerformed
        partida.crearTablero(5);
    }//GEN-LAST:event_rbtnCincoActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        if (!(rbtnCinco.isSelected() || rbtnTres.isSelected())) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado el tamaño del tablero.");
        } else if(this.listaJ1.getSelectedValue() == null || this.listaJ2.getSelectedValue() == null){
            JOptionPane.showMessageDialog(this, "Debe escojer un jugador de cada lista.");
        } 
        else if(this.listaJ1.getSelectedValue()==this.listaJ2.getSelectedValue()){
            JOptionPane.showMessageDialog(this, "Debe escojer un jugador diferente de cada lista.");
        }
        else {
            JFramePantallaDelTablero i = new JFramePantallaDelTablero(this.partida);
            i.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        String[] sino = {"Si", "No"};
        int eleccion = JOptionPane.showOptionDialog(this,
                "¿Está seguro que desea volver al menú principal?",
                "¿Desea volver al menú anterior?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                sino,
                "Si");
        if (eleccion == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    private void listaJ2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaJ2FocusLost
        if (this.listaJ1.getSelectedValue() != null && this.listaJ2.getSelectedValue() != null) {
            if (this.listaJ1.getSelectedValue().equals(this.listaJ2.getSelectedValue())) {
                this.mensajeAlerta.setVisible(true);

            } else {
                this.mensajeAlerta.setVisible(false);
            }
        }
        for (int i = 0; i < this.juego.getListaJugadores().size(); i++) {
            if (this.juego.getListaJugadores().get(i).getAlias().equals(this.listaJ2.getSelectedValue())) {
                this.partida.setJugadorRojo(this.juego.getListaJugadores().get(i));
            }
        }
    }//GEN-LAST:event_listaJ2FocusLost

    private void listaJ1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaJ1FocusLost
        if (this.listaJ1.getSelectedValue() != null && this.listaJ2.getSelectedValue() != null) {
            if (this.listaJ1.getSelectedValue().equals(this.listaJ2.getSelectedValue())) {
                this.mensajeAlerta.setVisible(true);

            } else {
                this.mensajeAlerta.setVisible(false);
            }
        }
        for (int i = 0; i < this.juego.getListaJugadores().size(); i++) {
            if (this.juego.getListaJugadores().get(i).getAlias().equals(this.listaJ1.getSelectedValue())) {
                this.partida.setJugadorAzul(this.juego.getListaJugadores().get(i));
            }
        }
    }//GEN-LAST:event_listaJ1FocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JList<String> listaJ1;
    private javax.swing.JList<String> listaJ2;
    private javax.swing.JLabel mensajeAlerta;
    private javax.swing.JRadioButton rbtnCinco;
    private javax.swing.JRadioButton rbtnTres;
    // End of variables declaration//GEN-END:variables
}
