package interfaz;

import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import obligatoriop2.*;

public class JFrameMenuPrincip extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenuPrincip
     */
    private Juego juego;
    private boolean mute;

    public void setMute(boolean unMute) {
        this.mute = unMute;
    }

    public JFrameMenuPrincip(Juego unJuego) {
        initComponents();
        this.juego = unJuego;

        this.setSize(410, 300);
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        this.btnJugar.setSize(100, 30);
        this.btnRanking.setSize(100, 30);
        this.btnRegistrar.setSize(100, 30);
        this.btnSalir.setSize(100, 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/BtnSalir2.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(250, 230, 129, 39);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Titulo (2).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 391, 46);

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/btnJugar (2).png"))); // NOI18N
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar);
        btnJugar.setBounds(150, 90, 147, 39);

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/RegistroJugadores.png"))); // NOI18N
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(150, 130, 147, 40);

        btnRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/BtnRanking.png"))); // NOI18N
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        getContentPane().add(btnRanking);
        btnRanking.setBounds(150, 169, 147, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Background.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(410, 320));
        jLabel2.setMinimumSize(new java.awt.Dimension(410, 320));
        jLabel2.setPreferredSize(new java.awt.Dimension(410, 320));
        jLabel2.setRequestFocusEnabled(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 410, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        if (this.juego.getListaJugadores().size() < 2) {
            JOptionPane.showMessageDialog(this, "Para jugar debe haber al menos 2 jugadores registrados.");
        } else {
            JFramePrePartida i = new JFramePrePartida(this.juego, new Partida());
            i.setVisible(true);
        }
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        String[] sino = {"Si", "No"};
        int eleccion = JOptionPane.showOptionDialog(this,
                "¿Está seguro que desea salir del juego?",
                "¿Salir?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                sino,
                "Si");
        if (eleccion == 0) {
            formWindowClosing(null);
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        JFrameRegistroDeJugador i = new JFrameRegistroDeJugador(this.juego);
        i.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        if (juego.ranking().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Aún no hay ningun jugador registrado");
        } else {
            JFrameRanking i = new JFrameRanking(this.juego);
            i.setVisible(true);
        }
    }//GEN-LAST:event_btnRankingActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Serializacion

        try {
            FileOutputStream f = new FileOutputStream("datos.txt");
            BufferedOutputStream l = new BufferedOutputStream(f);
            ObjectOutputStream o = new ObjectOutputStream(l);

            o.writeObject(this.juego);

            o.flush();
            o.close();
        } catch (Exception e) {
            System.out.println(" " + e);
        }
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
